name: uppercut_fantube
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^2.0.1

  #UI
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5 # 로딩 UI 처리 관련
  scroll_app_bar: ^2.0.0 # 스크롤 앱 바
  cupertino_will_pop_scope: ^1.2.1 # iOS Android swipe back method 관련
  flutter_svg: ^1.1.6 # Svg 아이콘 처리 관련
  cached_network_image: ^3.2.2 # 네트워크 이미지 처리 관련
  carousel_slider: ^4.1.1 # 슬라이더
  shimmer_animation: ^2.1.0+1 # Skeleton 처리 위젯
  url_launcher: ^6.1.6 #Url 런처
  flutter_styled_toast: ^2.1.3 # 토스트
  infinite_scroll_pagination: ^3.2.0 #Pagination
  polygon: ^0.1.0 # 다각형
  flutter_staggered_grid_view: ^0.6.2 # 그리드뷰

  #State Controller
  get: ^4.6.5


  #Network
  video_url_validator: ^1.0.2
  youtube_explode_dart: ^1.12.3 # 유튜브 meta data
  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.6
  json_annotation: ^4.7.0
  async: ^2.9.0

  #Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1


  #Local Storage
  sembast: ^3.4.0+6


  #Auth
  google_sign_in: ^5.4.4


  #Utils
  either_dart: ^0.3.0
  intl: ^0.17.0 # DATE




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Generators
  build_runner: ^2.1.11
  json_serializable: ^6.5.4
  retrofit_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/mocks/


  fonts:
    - family: pretendard_bold
      fonts:
        - asset: fonts/Pretendard-Bold.otf

    - family: pretendard_semiBold
      fonts:
        - asset: fonts/Pretendard-SemiBold.otf

    - family: pretendard_regular
      fonts:
        - asset: fonts/Pretendard-Regular.otf

    - family: pretendard_medium
      fonts:
        - asset: fonts/Pretendard-Medium.otf

    - family: staatliches_regular
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
