name: uppercut_fantube
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^2.0.1

  #UI
  cupertino_icons: ^1.0.2
  cupertino_will_pop_scope: ^1.2.1 # iOS Android swipe back method 관련
  get: ^4.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: pretendard_bold
      fonts:
        - asset: fonts/Pretendard-Bold.otf

    - family: pretendard_semiBold
      fonts:
        - asset: fonts/Pretendard-SemiBold.otf

    - family: pretendard_regular
      fonts:
        - asset: fonts/Pretendard-Regular.otf

    - family: pretendard_medium
      fonts:
        - asset: fonts/Pretendard-Medium.otf
