// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_KolUuNZziRow5pjFHgD2RX5miTjcUmY',
    appId: '1:1061021294637:web:4e2e366eabbede58d418a4',
    messagingSenderId: '1061021294637',
    projectId: 'soonsak-15350',
    authDomain: 'soonsak-15350.firebaseapp.com',
    databaseURL: 'https://soonsak-15350-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soonsak-15350.appspot.com',
    measurementId: 'G-W154CJ1TY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8uLI0nazM-2o9y1-mvSmi9vXrNEPl2Fo',
    appId: '1:1061021294637:android:c89bd4094ac7a778d418a4',
    messagingSenderId: '1061021294637',
    projectId: 'soonsak-15350',
    databaseURL: 'https://soonsak-15350-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soonsak-15350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKuFSxnz3HVm8EJpsKx55_3QWqZXKg7H0',
    appId: '1:1061021294637:ios:68b27f3b476537fed418a4',
    messagingSenderId: '1061021294637',
    projectId: 'soonsak-15350',
    databaseURL: 'https://soonsak-15350-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soonsak-15350.appspot.com',
    androidClientId: '1061021294637-7illq6jigflrj08cbkbi8jmjep8l9eel.apps.googleusercontent.com',
    iosClientId: '1061021294637-i1qloceu0r1lrfo3ic22ps83pqg5ta6v.apps.googleusercontent.com',
    iosBundleId: 'com.soonSak',
  );
}
