// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgt43UjgzQPA4OIcttxKajMq78yVryfpY',
    appId: '1:436064136115:android:91bfb65316f279451139c6',
    messagingSenderId: '436064136115',
    projectId: 'soonsakdev',
    databaseURL: 'https://soonsakdev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soonsakdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWE2lqZiL7j38l9ZQuCXm5ZtlciENf4DU',
    appId: '1:436064136115:ios:2a208d2980ea0db11139c6',
    messagingSenderId: '436064136115',
    projectId: 'soonsakdev',
    databaseURL: 'https://soonsakdev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soonsakdev.appspot.com',
    iosClientId: '436064136115-rdfg913k6usfca27j54segdvaq9gl2u3.apps.googleusercontent.com',
    iosBundleId: 'com.soonSak',
  );
}
