// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_KolUuNZziRow5pjFHgD2RX5miTjcUmY',
    appId: '1:1061021294637:web:e788020552d163ead418a4',
    messagingSenderId: '1061021294637',
    projectId: 'soonsak-15350',
    authDomain: 'soonsak-15350.firebaseapp.com',
    storageBucket: 'soonsak-15350.appspot.com',
    measurementId: 'G-6XXEB74JML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8uLI0nazM-2o9y1-mvSmi9vXrNEPl2Fo',
    appId: '1:1061021294637:android:3ba1e53928812837d418a4',
    messagingSenderId: '1061021294637',
    projectId: 'soonsak-15350',
    storageBucket: 'soonsak-15350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKuFSxnz3HVm8EJpsKx55_3QWqZXKg7H0',
    appId: '1:1061021294637:ios:e087ac5654812d2cd418a4',
    messagingSenderId: '1061021294637',
    projectId: 'soonsak-15350',
    storageBucket: 'soonsak-15350.appspot.com',
    iosClientId: '1061021294637-nfaepoo23u3lic7s0hchdp3dic1ho4hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.uppercutFantube',
  );
}
